frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.23.2/30
!
interface lo
 ip address 192.0.2.3/32
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.0.23.1 remote-as 65002
 !
 address-family ipv4 unicast
  network 192.0.2.3/32
  neighbor 10.0.23.1 activate
 exit-address-family
exit
!
line vty
!
